#ifndef TEST_H 
#define TEST_H


#define LED_1_STATE_PARAMETER_NAME 	 "LED_1_STATE"
#define LED_1_STATE_DEVICE_NUMBER 	 0
#define LED_1_STATE_REGISTER_NUMBER 	 0
#define LED_1_STATE_START_BIT 	 0
#define LED_1_STATE_BITFIELD_LENGTH 	 1
#define LED_1_STATE_DATATYPE 	 0
#define LED_1_STATE_DATATYPE_STRING 	 "BOOL"


#define LED_2_STATE_PARAMETER_NAME 	 "LED_2_STATE"
#define LED_2_STATE_DEVICE_NUMBER 	 0
#define LED_2_STATE_REGISTER_NUMBER 	 0
#define LED_2_STATE_START_BIT 	 1
#define LED_2_STATE_BITFIELD_LENGTH 	 1
#define LED_2_STATE_DATATYPE 	 0
#define LED_2_STATE_DATATYPE_STRING 	 "BOOL"


#define LED_3_STATE_PARAMETER_NAME 	 "LED_3_STATE"
#define LED_3_STATE_DEVICE_NUMBER 	 0
#define LED_3_STATE_REGISTER_NUMBER 	 0
#define LED_3_STATE_START_BIT 	 2
#define LED_3_STATE_BITFIELD_LENGTH 	 1
#define LED_3_STATE_DATATYPE 	 0
#define LED_3_STATE_DATATYPE_STRING 	 "BOOL"


#define LED_4_STATE_PARAMETER_NAME 	 "LED_4_STATE"
#define LED_4_STATE_DEVICE_NUMBER 	 0
#define LED_4_STATE_REGISTER_NUMBER 	 0
#define LED_4_STATE_START_BIT 	 3
#define LED_4_STATE_BITFIELD_LENGTH 	 1
#define LED_4_STATE_DATATYPE 	 0
#define LED_4_STATE_DATATYPE_STRING 	 "BOOL"


#define LED_1_COMMAND_PARAMETER_NAME 	 "LED_1_COMMAND"
#define LED_1_COMMAND_DEVICE_NUMBER 	 0
#define LED_1_COMMAND_REGISTER_NUMBER 	 0
#define LED_1_COMMAND_START_BIT 	 4
#define LED_1_COMMAND_BITFIELD_LENGTH 	 2
#define LED_1_COMMAND_DATATYPE 	 1
#define LED_1_COMMAND_DATATYPE_STRING 	 "UINT"


#define LED_2_COMMAND_PARAMETER_NAME 	 "LED_2_COMMAND"
#define LED_2_COMMAND_DEVICE_NUMBER 	 0
#define LED_2_COMMAND_REGISTER_NUMBER 	 0
#define LED_2_COMMAND_START_BIT 	 6
#define LED_2_COMMAND_BITFIELD_LENGTH 	 2
#define LED_2_COMMAND_DATATYPE 	 1
#define LED_2_COMMAND_DATATYPE_STRING 	 "UINT"


#define LED_3_COMMAND_PARAMETER_NAME 	 "LED_3_COMMAND"
#define LED_3_COMMAND_DEVICE_NUMBER 	 0
#define LED_3_COMMAND_REGISTER_NUMBER 	 0
#define LED_3_COMMAND_START_BIT 	 8
#define LED_3_COMMAND_BITFIELD_LENGTH 	 2
#define LED_3_COMMAND_DATATYPE 	 1
#define LED_3_COMMAND_DATATYPE_STRING 	 "UINT"


#define LED_4_COMMAND_PARAMETER_NAME 	 "LED_4_COMMAND"
#define LED_4_COMMAND_DEVICE_NUMBER 	 0
#define LED_4_COMMAND_REGISTER_NUMBER 	 0
#define LED_4_COMMAND_START_BIT 	 10
#define LED_4_COMMAND_BITFIELD_LENGTH 	 12
#define LED_4_COMMAND_DATATYPE 	 1
#define LED_4_COMMAND_DATATYPE_STRING 	 "UINT"


#define LED_BLINK_INTERVAL_MS_PARAMETER_NAME 	 "LED_BLINK_INTERVAL_MS"
#define LED_BLINK_INTERVAL_MS_DEVICE_NUMBER 	 0
#define LED_BLINK_INTERVAL_MS_REGISTER_NUMBER 	 0
#define LED_BLINK_INTERVAL_MS_START_BIT 	 12
#define LED_BLINK_INTERVAL_MS_BITFIELD_LENGTH 	 16
#define LED_BLINK_INTERVAL_MS_DATATYPE 	 1
#define LED_BLINK_INTERVAL_MS_DATATYPE_STRING 	 "UINT"

#endif /* TEST_H */

